### ISSUE TITLE
无法切入Toast等系统类

### ISSUE THREAD

**Issue by Lok1n8** [Ysj001/bcu-modifier-aspect#1]
`    @Pointcut(
        target = "class:android/widget/Toast", // 切入的目标方法所在的类
        funName = "show", // 切入的目标方法名
        funDesc = ".*.", // 切入的目标方法描述，这里的正则表示任意描述
        position = POSITION_START, // 定义切入位置，这里表示在目标方法开始处
    )
    fun test1(cp: JoinPoint) {
        "test1 ${cp.target}".loge()
    }`

**Comment by Ysj001** [comment]
系统类是无法修改的，但是提供了方法可以支持代理其调用。
如果你想监控或代理所有 Toast 调用可以将 position = POSITION_CALL。
详见 demo 例子：https://github.com/Ysj001/bcu-modifier-aspect/blob/main/app/src/main/java/com/ysj/demo/aspect/AspectDemo.kt#L64

**Comment by Lok1n8** [comment]
了解了 测试后POSITION_CALL可用。 感谢
