### ISSUE TITLE
如何切入构造方法

### ISSUE THREAD

**Issue by Lok1n8** [Ysj001/bcu-modifier-aspect#2]
我试了一下 < init > 不行

**Comment by Lok1n8** [comment]
没事了 clean一下就有了

**Comment by Ysj001** [comment]
gradle 的编译缓存通常只在有代码修改后才失效，因此如果只是更改 gradle 构建配置可能不会触发模块重新编译，此时若不想完全 clean 可以在某代码位置加个换行之类的
