### ISSUE TITLE
你好 这个好像不能代理Init方法

### ISSUE THREAD

**Issue by Lok1n8** [Ysj001/bcu-modifier-aspect#3]
![zz](https://github.com/Ysj001/bcu-modifier-aspect/assets/23357769/b3e73f27-affa-4470-8629-cff67fa5c915)
比如这里有一个异常，new他就会报错。
随便一个地方new他
![zzz](https://github.com/Ysj001/bcu-modifier-aspect/assets/23357769/4431eea9-2208-4965-ba51-0028d535e4d8)
切入点为
![zzzzzzzzz](https://github.com/Ysj001/bcu-modifier-aspect/assets/23357769/2e820110-e04e-4111-aa8c-395519f794a2)

**Comment by Lok1n8** [comment]
反编译出来的就会是这样子的
<img width="876" alt="1456" src="https://github.com/Ysj001/bcu-modifier-aspect/assets/23357769/4a943255-15e4-4ffc-a88d-8a32c6d1c2f1">

**Comment by Ysj001** [comment]
好的，已经核实并于 1.0.0-beta3 中修复
